package com.toad.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.toad.entities.Director;
import com.toad.repositories.DirectorRepository;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;

@Controller
@RequestMapping(path = "/toad/director")
public class DirectorController {
  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private DirectorRepository directorRepository;

  @PostMapping(path = "/add")
  public @ResponseBody String addNewDirector(@RequestParam Integer director_id, @RequestParam String nom,
      @RequestParam String prenom, @RequestParam Timestamp date_naissance, @RequestParam String nationalite) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Director n = new Director();
    n.setdirector_id(director_id);
    n.setnom(nom);
    n.setprenom(prenom);
    
    // Convertir Timestamp en String
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    String dateNaissanceStr = sdf.format(date_naissance);
    n.setdate_naissance(date_naissance); // Utiliser directement date_naissance de type Timestamp

    n.setnationalite(nationalite);
    directorRepository.save(n);
    return "Saved";
  }

  @GetMapping(path = "/all")
  public @ResponseBody Iterable<Director> getAllDirectors() {
    // This returns a JSON or XML with the users
    return directorRepository.findAll();
  }

  @GetMapping(path = "/getById")
  public @ResponseBody Director getDirectorById(@RequestParam Integer id) {
    Director director = directorRepository.findById(id).orElse(null);
    if (director != null) {
      Director filteredDirector = new Director();
      filteredDirector.setdirector_id(director.getdirector_id());
      filteredDirector.setnom(director.getnom());
      filteredDirector.setprenom(director.getprenom());
      filteredDirector.setdate_naissance(director.getdate_naissance());
      filteredDirector.setnationalite(director.getnationalite());
      return filteredDirector;
    }
    return null;
  }

  @DeleteMapping(path = "/delete/{director_id}")
  public @ResponseBody String deleteDirector(@PathVariable Integer director_id) {
    String status = null;
    if (directorRepository.existsById(director_id)) {
        directorRepository.deleteById(director_id);
        status = "Réalisateur supprimé";
    } else {
        status = "Réalisateur pas trouvé";
    }
    return status;
  }

  @PutMapping(path = "/add")
  public @ResponseBody String PutDirector(@RequestParam Integer director_id, @RequestParam String nom,
      @RequestParam String prenom, @RequestParam java.sql.Timestamp date_naissance, @RequestParam String nationalite) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request
    return null; // Placeholder return, actual implementation needed
  }
}